### PR TITLE
add support for google analytics display features

### PR DESCRIPTION
**Pull request by mortada**
Details can be seen here: https://support.google.com/analytics/answer/2444872?hl=en&utm_id=ad 

A new variable called `GOOGLE_ANALYTICS_DISPLAY_FEATURES` here enables the display features. This works for both the new universal analytics or the classical google analytics.

### CODE REVIEW

**Comment by duilio** [comment]
Thanks

**Comment by duilio** [comment]
I've forgot to ask you to add a simple sentence in the README in order to let other people know about this settings. May you provide it? Also, I've seen you have tons of pull request, it may be a good thing to put your name in the author list that is in the same file.

**Comment by mortada** [comment]
@duilio Sure I'm happy to. I'll make a pull request to update the README shortly.

**Comment by mortada** [comment]
please see the pull request here https://github.com/duilio/pelican-octopress-theme/pull/68, thanks!

**Pull request merged**
