### PR TITLE
fixed google search

### PR DESCRIPTION
**Pull request by mstreuhofer**

### CODE REVIEW

**Comment by mstreuhofer** [comment]
any thoughts on this PR's future?

**Comment by mstreuhofer** [comment]
no time only now or no interest and i should close the PR?

**Comment by dhermes** [comment]
@duilio Would it make more sense to have someone else with more time take over as the official fork?

**Comment by duilio** [comment]
@dhermes Probably it would make more sense to add a maintainer instead of fork.

**Pull request merged**
